In [2]:
import numpy as np

In [5]:
# 创建一维数组
a = np.array([1, 2, 3, 4, 5])
# 创建二维数组
a2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)
print(a2)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
# 将源数组打乱顺序
a = np.array([1, 2, 3, 4, 5])
shuffle_indices = np.random.permutation(len(a))
b = a[shuffle_indices]
print(a)
print(b)

[1 2 3 4 5]
[1 4 2 5 3]


In [11]:
# 创建等差数列
a = np.linspace(0, 10, 5)  # 生成首位是0，末位为10，并且含有5个元素的等差数列，即公差=(10-0)/(5-1)
print(a)

[ 0.   2.5  5.   7.5 10. ]
